package equationprogram;
import javax.swing.*;

/**
 * The GUI of the application.
 * @author Sami Safadi
 */
public class WindowArabic extends javax.swing.JFrame {
    private QuadricEq e1;
    private QuadricEqPlot p1;
    private JFrame f;
    
    /**
     * Creates new form MainWindow
     */
    public WindowArabic() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextC = new javax.swing.JTextField();
        jPanelSolve = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSolve = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanelDraw = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextX1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextX2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextY1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextY2 = new javax.swing.JTextField();
        jButtonDraw = new javax.swing.JButton();
        jPanelOutput = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextEqType = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextRoot1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextRoot2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("برنامج حل المعادلات من الدرجة الثانية");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("المعادلة من الدرجة الثانية ولها الشكل أ س2 + ب س + ج = 0");

        org.jdesktop.layout.GroupLayout jPanelInfoLayout = new org.jdesktop.layout.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("أدخل قيمة أ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextA.setNextFocusableComponent(jTextB);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("أدخل قيمة ب");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextB.setNextFocusableComponent(jTextC);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("أدخل قيمة ج");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextC.setNextFocusableComponent(jButtonSolve);

        org.jdesktop.layout.GroupLayout jPanelInputLayout = new org.jdesktop.layout.GroupLayout(jPanelInput);
        jPanelInput.setLayout(jPanelInputLayout);
        jPanelInputLayout.setHorizontalGroup(
            jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextA, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextC, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                .addContainerGap())
        );

        jPanelInputLayout.linkSize(new java.awt.Component[] {jLabel1, jLabel2, jLabel3}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanelInputLayout.setVerticalGroup(
            jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelInputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSolve.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jPanelButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelButtons.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jButtonSolve.setText("حل المعادلة");
        jButtonSolve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSolve.setNextFocusableComponent(jTextX1);
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveEquation(evt);
            }
        });
        jPanelButtons.add(jButtonSolve);

        jButtonAbout.setText("عن المؤلف");
        jButtonAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbout.setNextFocusableComponent(jButtonExit);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAbout(evt);
            }
        });
        jPanelButtons.add(jButtonAbout);

        jButtonExit.setText("خروج");
        jButtonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExit.setNextFocusableComponent(jTextA);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit(evt);
            }
        });
        jPanelButtons.add(jButtonExit);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("على المحور x من");

        jTextX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextX1.setText("-100");
        jTextX1.setNextFocusableComponent(jTextX2);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("إلى");

        jTextX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextX2.setText("+100");
        jTextX2.setNextFocusableComponent(jTextY1);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("على المحور y من");

        jTextY1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextY1.setText("-100");
        jTextY1.setNextFocusableComponent(jTextY2);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("إلى");

        jTextY2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextY2.setText("+100");
        jTextY2.setNextFocusableComponent(jButtonDraw);

        jButtonDraw.setText("رسم الخط البياني للتابع الموافق");
        jButtonDraw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDraw.setNextFocusableComponent(jButtonAbout);
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotFunction(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelDrawLayout = new org.jdesktop.layout.GroupLayout(jPanelDraw);
        jPanelDraw.setLayout(jPanelDrawLayout);
        jPanelDrawLayout.setHorizontalGroup(
            jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelDrawLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButtonDraw, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .add(jPanelDrawLayout.createSequentialGroup()
                        .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextX2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextY2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel8)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextX1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextY1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7))))
                .addContainerGap())
        );

        jPanelDrawLayout.linkSize(new java.awt.Component[] {jLabel5, jLabel7}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanelDrawLayout.linkSize(new java.awt.Component[] {jLabel6, jLabel8}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanelDrawLayout.setVerticalGroup(
            jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDrawLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jTextX2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextX1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jTextY1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(jTextY2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(jButtonDraw)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanelSolveLayout = new org.jdesktop.layout.GroupLayout(jPanelSolve);
        jPanelSolve.setLayout(jPanelSolveLayout);
        jPanelSolveLayout.setHorizontalGroup(
            jPanelSolveLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelSolveLayout.createSequentialGroup()
                .add(jPanelDraw, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        jPanelSolveLayout.setVerticalGroup(
            jPanelSolveLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDraw, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jPanelButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jPanelSolveLayout.linkSize(new java.awt.Component[] {jPanelButtons, jPanelDraw}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanelOutput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("نوع المعادلة");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextEqType.setEditable(false);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("الجذر الأول");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextRoot1.setEditable(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("الجذر الثاني");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextRoot2.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanelOutputLayout = new org.jdesktop.layout.GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOutputLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextEqType, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextRoot1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextRoot2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel11))
                .addContainerGap())
        );

        jPanelOutputLayout.linkSize(new java.awt.Component[] {jLabel10, jLabel11, jLabel9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOutputLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jTextEqType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jTextRoot1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jTextRoot2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelSolve, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelOutput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelSolve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOutput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolveEquation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveEquation
        double a,b,c;
        
        a = Double.parseDouble(jTextA.getText());
        b = Double.parseDouble(jTextB.getText());
        c = Double.parseDouble(jTextC.getText());
        
        //creates an equation and solve it
        e1 = new QuadricEq(a,b,c);
        
        //display the roots
        jTextRoot1.setText(e1.getRoot1());
        jTextRoot2.setText(e1.getRoot2());
        jTextEqType.setText(e1.getType());
    }//GEN-LAST:event_SolveEquation

    private void PlotFunction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotFunction
        double x1,x2,y1,y2;
        x1 = Double.parseDouble(jTextX1.getText());
        x2 = Double.parseDouble(jTextX2.getText());
        y1 = Double.parseDouble(jTextY1.getText());
        y2 = Double.parseDouble(jTextY2.getText());
        
        //Create a new plot object
        p1= new QuadricEqPlot(e1,x1,x2,y1,y2);
        
        //Create a new plot frame, and add the plot object to it
        f= new JFrame("Plotting the equation: " + e1 );
        f.setSize(p1.getWidth(),p1.getHeight());
        f.getContentPane().add(p1);
        f.setLocation(100,100);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setVisible(true);
    }//GEN-LAST:event_PlotFunction

    private void Exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit
    System.exit(0);
    }//GEN-LAST:event_Exit

    private void ShowAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAbout
        String message = "Programmed by Sami Safadi.";
        JOptionPane.showMessageDialog(this, message, "About us", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ShowAbout
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WindowArabic().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDraw;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JPanel jPanelSolve;
    private javax.swing.JTextField jTextA;
    private javax.swing.JTextField jTextB;
    private javax.swing.JTextField jTextC;
    private javax.swing.JTextField jTextEqType;
    private javax.swing.JTextField jTextRoot1;
    private javax.swing.JTextField jTextRoot2;
    private javax.swing.JTextField jTextX1;
    private javax.swing.JTextField jTextX2;
    private javax.swing.JTextField jTextY1;
    private javax.swing.JTextField jTextY2;
    // End of variables declaration//GEN-END:variables
    
}
