package equationprogram;
import javax.swing.*;

/**
 * The GUI of the application.
 * @author Sami Safadi
 */
public class WindowArabic extends javax.swing.JFrame {
    private QuadricEq e1;
    private QuadricEqPlot p1;
    private JFrame f;
    
    /**
     * Creates new form MainWindow
     */
    public WindowArabic() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelInput = new javax.swing.JPanel();
        jTextC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jButtonDraw = new javax.swing.JButton();
        jButtonSolve = new javax.swing.JButton();
        jPanelDraw = new javax.swing.JPanel();
        jTextY2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextY1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextX2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextX1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanelOutput = new javax.swing.JPanel();
        jTextEqType = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextRoot2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextRoot1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("برنامج حل المعادلات الشهير من سامي صفدي");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanelInfo.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanelInfo.setMinimumSize(null);
        jPanelInfo.setPreferredSize(null);
        jPanelInfo.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("المعادلة من الدرجة الثانية ولها الشكل أ س2 + ب س + ج = 0");
        jPanelInfo.add(jLabel4, "card2");

        getContentPane().add(jPanelInfo);

        jPanelInput.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanelInput.setMinimumSize(null);
        jPanelInput.setPreferredSize(null);
        jPanelInput.setLayout(new java.awt.GridBagLayout());

        jTextC.setMinimumSize(new java.awt.Dimension(50, 19));
        jTextC.setNextFocusableComponent(jButtonSolve);
        jTextC.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelInput.add(jTextC, new java.awt.GridBagConstraints());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("أدخل قيمة ج");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelInput.add(jLabel3, new java.awt.GridBagConstraints());

        jTextB.setMinimumSize(new java.awt.Dimension(50, 19));
        jTextB.setNextFocusableComponent(jTextC);
        jTextB.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelInput.add(jTextB, new java.awt.GridBagConstraints());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("أدخل قيمة ب");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelInput.add(jLabel2, new java.awt.GridBagConstraints());

        jTextA.setMinimumSize(new java.awt.Dimension(50, 19));
        jTextA.setNextFocusableComponent(jTextB);
        jTextA.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelInput.add(jTextA, new java.awt.GridBagConstraints());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("أدخل قيمة أ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelInput.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelInput);

        jPanelButtons.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanelButtons.setMinimumSize(null);
        jPanelButtons.setPreferredSize(null);
        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jButtonExit.setText("خروج");
        jButtonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExit.setNextFocusableComponent(jTextA);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit(evt);
            }
        });
        jPanelButtons.add(jButtonExit, new java.awt.GridBagConstraints());

        jButtonAbout.setText("عن المؤلف");
        jButtonAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbout.setNextFocusableComponent(jButtonExit);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAbout(evt);
            }
        });
        jPanelButtons.add(jButtonAbout, new java.awt.GridBagConstraints());

        jButtonDraw.setText("رسم الخط البياني للتابع الموافق");
        jButtonDraw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDraw.setNextFocusableComponent(jButtonAbout);
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotFunction(evt);
            }
        });
        jPanelButtons.add(jButtonDraw, new java.awt.GridBagConstraints());

        jButtonSolve.setText("حل المعادلة");
        jButtonSolve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSolve.setNextFocusableComponent(jTextX1);
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveEquation(evt);
            }
        });
        jPanelButtons.add(jButtonSolve, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelButtons);

        jPanelDraw.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanelDraw.setMinimumSize(null);
        jPanelDraw.setPreferredSize(null);
        jPanelDraw.setLayout(new java.awt.GridBagLayout());

        jTextY2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextY2.setText("+100");
        jTextY2.setNextFocusableComponent(jButtonDraw);
        jTextY2.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanelDraw.add(jTextY2, new java.awt.GridBagConstraints());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("إلى");
        jPanelDraw.add(jLabel8, new java.awt.GridBagConstraints());

        jTextY1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextY1.setText("-100");
        jTextY1.setNextFocusableComponent(jTextY2);
        jTextY1.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanelDraw.add(jTextY1, new java.awt.GridBagConstraints());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("على المحور y من");
        jPanelDraw.add(jLabel7, new java.awt.GridBagConstraints());

        jTextX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextX2.setText("+100");
        jTextX2.setNextFocusableComponent(jTextY1);
        jTextX2.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanelDraw.add(jTextX2, new java.awt.GridBagConstraints());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("إلى");
        jPanelDraw.add(jLabel6, new java.awt.GridBagConstraints());

        jTextX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextX1.setText("-100");
        jTextX1.setNextFocusableComponent(jTextX2);
        jTextX1.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanelDraw.add(jTextX1, new java.awt.GridBagConstraints());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("على المحور x من");
        jPanelDraw.add(jLabel5, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelDraw);

        jPanelOutput.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanelOutput.setMinimumSize(null);
        jPanelOutput.setPreferredSize(null);
        jPanelOutput.setLayout(new java.awt.GridBagLayout());

        jTextEqType.setEditable(false);
        jTextEqType.setPreferredSize(new java.awt.Dimension(70, 19));
        jPanelOutput.add(jTextEqType, new java.awt.GridBagConstraints());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("نوع المعادلة");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelOutput.add(jLabel9, new java.awt.GridBagConstraints());

        jTextRoot2.setEditable(false);
        jTextRoot2.setPreferredSize(new java.awt.Dimension(70, 19));
        jPanelOutput.add(jTextRoot2, new java.awt.GridBagConstraints());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("الجذر الثاني");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelOutput.add(jLabel11, new java.awt.GridBagConstraints());

        jTextRoot1.setEditable(false);
        jTextRoot1.setPreferredSize(new java.awt.Dimension(70, 19));
        jPanelOutput.add(jTextRoot1, new java.awt.GridBagConstraints());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("الجذر الأول");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelOutput.add(jLabel10, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelOutput);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolveEquation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveEquation
        double a,b,c;
        
        a = Double.parseDouble(jTextA.getText());
        b = Double.parseDouble(jTextB.getText());
        c = Double.parseDouble(jTextC.getText());
        
        //creates an equation and solve it
        e1 = new QuadricEq(a,b,c);
        
        //display the roots
        jTextRoot1.setText(e1.getRoot1());
        jTextRoot2.setText(e1.getRoot2());
        jTextEqType.setText(e1.getType());
    }//GEN-LAST:event_SolveEquation

    private void PlotFunction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotFunction
        double x1,x2,y1,y2;
        x1 = Double.parseDouble(jTextX1.getText());
        x2 = Double.parseDouble(jTextX2.getText());
        y1 = Double.parseDouble(jTextY1.getText());
        y2 = Double.parseDouble(jTextY2.getText());
        
        //Create a new plot object
        p1= new QuadricEqPlot(e1,x1,x2,y1,y2);
        
        //Create a new plot frame, and add the plot object to it
        f= new JFrame("Plotting the equation: " + e1 );
        f.setSize(p1.getWidth(),p1.getHeight());
        f.getContentPane().add(p1);
        f.setLocation(100,100);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setVisible(true);
    }//GEN-LAST:event_PlotFunction

    private void Exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit
    System.exit(0);
    }//GEN-LAST:event_Exit

    private void ShowAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAbout
        String message = "Programmed by Sami Safadi.";
        JOptionPane.showMessageDialog(this, message, "About us", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ShowAbout
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WindowArabic().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDraw;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JTextField jTextA;
    private javax.swing.JTextField jTextB;
    private javax.swing.JTextField jTextC;
    private javax.swing.JTextField jTextEqType;
    private javax.swing.JTextField jTextRoot1;
    private javax.swing.JTextField jTextRoot2;
    private javax.swing.JTextField jTextX1;
    private javax.swing.JTextField jTextX2;
    private javax.swing.JTextField jTextY1;
    private javax.swing.JTextField jTextY2;
    // End of variables declaration//GEN-END:variables
    
}
